traveller_travel_advisor_homepage:
    path:     /
    defaults: { _controller: TravellerTravelAdvisorBundle:Default:index }

traveller_travel_advisor_voyage:
    path:     /voyage
    defaults: { _controller: TravellerTravelAdvisorBundle:Default:voyage }

traveller_travel_advisor_admin:
    path:     /admin
    defaults: { _controller: TravellerTravelAdvisorBundle:Default:admin }

traveller_travel_advisor_voyagePrenom:
    path:     /voyage/{prenom}
    defaults: { _controller: TravellerTravelAdvisorBundle:Default:voyagePrenom }
    requirements:
            _method: GET
            prenom: \w+

traveller_travel_advisor_adminRedirect:
    path:     /admin/redirection
    defaults: { _controller: TravellerTravelAdvisorBundle:Default:adminRedirect }